development:
  dialect: mysql
  # datasource: ${DB_USER}:${DB_PASS}@tcp(${DB_HOST}:${DB_PORT})/${DB_NAME}?parseTime=true
  datasource: root:tsm12345@tcp(localhost:3306)/belajar?parseTime=true
  dir: migration/
